### ISSUE TITLE
Modules TODO

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.pacemaker#5]
Add pacemaker_resource and pacemaker_sync modules

**Comment by rhysmeister** [comment]
**pacemaker_resource**
resource_config is a dict flattened to kv pairs...

```
- name: Create myFS resource
  pacemaker_resource:
    resource_name: myFS
    resource_type: FileSystem
    resource_config:
      device: 'nfs_server:/export/www'
      directory: '/www'
      fstype: 'nfs'
    resource_group: apache
    state: present

- name: Create floating ip resource
  pacemaker_resource:
    resource_name: ClusterIP
    resource_type: ocf:heartbeat:apache
    resource_config:
      ip: 192.168.122.120
    resource_group: apache
    state: present

- name: Create website
  pacemaker_resource:
    resource_name: website 
    resource_type: ocf:heartbeat:apache
    resource_config:
      configfile: /etc/httpd/conf/httpd.conf 
      statusurl: "http://localhost/server-status"
    resource_group: apache
    state: present
```
**pacemaker_property**

The use of stonith-enabled=false is completely inappropriate for a production cluster. It tells the cluster to simply pretend that failed nodes are safely fenced. 

```
- name: Only ever turn fencing off on a test cluster
  pacemaker_property:
    property_name: stonith-enabled
    property_value: false
```

**Comment by rhysmeister** [comment]
**pacemaker_node**

```
pacemaker_node:
  node: nodea.private.example.com
  state: maintenance|unmaintenance|standby|unstandby|utilization
  utilization:
    cpu: 4
    ram: 1G  # kv pair flatten, only valid when state = utilization

```
Probably get current info from `pcs status nodes` cmd.

**Comment by rhysmeister** [comment]
Modules done...

- pacemaker_property
- pacemaker_resources

TODO

- pacemaker_sync - Need for when the corosnyc file is updated... i.e. in pacemaker_cluster module.
- pacemaker_status - Useful for maint ops
- pacemaker_node

**Comment by rhysmeister** [comment]
**pacemaker_constraint**

```
- name: Create a location constraint
  community.pacemaker.pacemaker_constraint:
    name: myResource_prefers
    type: location
    perfers:
      node1:
      node2:
      node3: 

- name: Create a location constraint to avoid a node 
  community.pacemaker.pacemaker_constraint:
    name: myResource_avoids
    type: location
    avoids:
      node5:


- name: Start resources in a specific order
  community.pacemaker.pacemaker_constraint:
    name: myResource_start_order
    type: order
    ordering:
      - start: mounts
      - start: mysql
      - start: https

- name: Stop resources in a specific order
  community.pacemaker.pacemaker_constraint:
    name: myResource_stop_order
    type: order
    ordering:
      - stop: https
      - stop: mysql
      - stop: mounts


- name: Colocate resources
  community.pacemaker.pacemaker_constraint:
    name: myResource_colocation
    type: colocation
    resources:
      - https
      - mysql

- name: Remove a constraint
  community.pacemaker.pacemaker_constraint:
    name: myResource_colocation
    state: absent
```

**Comment by rhysmeister** [comment]
We need to do a bit of refactoring with the name/id (constraint id). At the moment we create the id from the name and the type...

```
- name: Create a location constraint
  community.pacemaker.pacemaker_constraint:
    name: myResource
    type: location
    prefers:
     - node1: 100
```

This task would create an id of "myResource_location". As there are different methods of adding constraints this strategy doesn't really work well. The name in this context is also used as the service to create the constraint on. Therefore we need to do the following...

- Ensure "name" becomes the unique id (to always be supplied by the user).
- Add a resource parameter to the module to be used when the type=location.
- Refactor the function that creates the constraints. Each constraint type should have it's own function where the cmd is built.
- Remove the get_constraint_id function.
- Refactor tests to use the changed name parameter with a unique name and update any location type tasks with a "resource" parameter.
- Refactor tests: remove the type param from the delete tests.
