### ISSUE TITLE
pacemaker_fence module

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.pacemaker#8]
##### SUMMARY
Add pacemaker_fence module

##### ISSUE TYPE
- Feature Idea

**Comment by rhysmeister** [comment]
The possibilities for VIrtualBox seem to be...

- fence_vbox (Not included in the CentOS default fence-agents package, probably due to licensing)
- fence_virt - Might work... have to try it.

References:

https://linbit.com/blog/using-fencing-in-pacemaker-clusters-on-virtualbox-hypervisors/
https://linux.die.net/man/8/fence_virt

**Comment by rhysmeister** [comment]
```
community.pacemaker.pacemaker_fence:
  fence_name: "{{ inventory_hostname }}_fence"  # default?
  fence_agent: "fence_vbox"  # potentially support other agents in the future?
  fence_config:
    ip: "192.168.1.101"
    login: "rhys"
    plug: "xxxx-xxxx-xxxx-xxxx"
    pcmk_host_list: "pacemaker-1"
    identity_file: "/path/to/id_rsa"
```

Config params for fence_vbox...

-     ip: the IP address the cluster nodes use to communicate with the hypervisor
-     login: the username on the hypervisor that the fence agents SSH into
-     plug: the UUID for the VM we’re configuring the fence agent for
-     pcmk_host_list: the VM’s hostname as used in the Pacemaker cluster (crm_node -n)
-     identity_file: the SSH key created for and used by the vbox_stonith user to login to the hypervisor
